version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana
    volumes:
      - ./data/kibana:/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  logstash: